In [ ]:
data={
    'Model':["SVM","KNN","Decison","Logistic"],
    'Train (Accuracy)':[55,90,93,89],
    'Test':[51,89,89,91],
    'Precision':[69,86,86,90],
    'Re-Call':[56,86,85,88],
    'f1-score':[50,86,85,89],
    'ROC-AUC':[68,91,88,87],
    'CV-Score':[62,86,86,88],
    'std':[8,3.8,2.07,4.0]
}

In [ ]:
import pandas as pd
model_selection = pd.DataFrame(data)

In [ ]:
model_selection

,Model,Train (Accuracy),Test,Precision,Re-Call,f1-score,ROC-AUC,CV-Score,std
0,SVM,55,51,69,56,50,68,62,8.00
1,KNN,90,89,86,86,86,91,86,3.80
2,Decison,93,89,86,85,85,88,86,2.07
3,Logistic,89,91,90,88,89,87,88,4.00

In [ ]:
model_selection['Rank']=[4,2,3,1]

In [ ]:
model_selection

,Model,Train (Accuracy),Test,Precision,Re-Call,f1-score,ROC-AUC,CV-Score,std,Rank
0,SVM,55,51,69,56,50,68,62,8.00,4
1,KNN,90,89,86,86,86,91,86,3.80,2
2,Decison,93,89,86,85,85,88,86,2.07,3
3,Logistic,89,91,90,88,89,87,88,4.00,1

In [ ]:
selected=model_selection.sort_values(by='Rank').head(2)
selected

,Model,Train (Accuracy),Test,Precision,Re-Call,f1-score,ROC-AUC,CV-Score,std,Rank
3,Logistic,89,91,90,88,89,87,88,4.0,1
1,KNN,90,89,86,86,86,91,86,3.8,2

In [ ]:
new_df = pd.DataFrame({
    'Model': ['logistic-h1','logistic-h2','KNN-h1','KNN-h2','logistic-h3'],
    'Train (Accuracy)': [92,92,93,93,],
    'Test': [93,93,91,80],
    'Precision': [94,94,88,77],
    'Re-Call': [89,89,87,80],
    'f1-score': [91,91,87,78],
    'ROC-AUC':[87,87,91,91],
    'CV-Score':[91,91,86,87],
    'std':[3.6,3.6,2.8,2.8]

})

df = pd.concat([selected, new_df], ignore_index=True)

In [ ]:
df

,Model,Train (Accuracy),Test,Precision,Re-Call,f1-score,ROC-AUC,CV-Score,std,Rank
0,Logistic,89,91,90,88,89,87,88,4.0,1.0
1,KNN,90,89,86,86,86,91,86,3.8,2.0
2,logistic-h1,92,93,94,89,91,87,91,3.6,NaN
3,logistic-h2,92,93,94,89,91,87,91,3.6,NaN
4,KNN-h1,93,91,88,87,87,91,86,2.8,NaN
5,KNN-h2,93,80,77,80,78,91,87,2.8,NaN

H1 logistic is the best model